[toolchain]
anchor_version = "0.29.0"    # `anchor-cli` version to use(requires `avm`)
solana_version = "1.18.12"

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_stake_market = "2saZdaCQioYutAv8aFXyLgnJWs2QSnMEFtvKGeUc4PUj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#wallet = "/Users/nico/Downloads/wallet-keypair.json"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
